osx_image: xcode10.0
language: objective-c
script: 
- git submodule update --init
- sh auto_make_env.sh
- sh b.sh --osx
- xcodebuild -workspace ./build_osx/gkENGINE.xcodeproj -scheme ALL_BUILD GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
after_success:

