matrix:
  include:
    - os: osx
      osx_image: xcode10
      language: objective-c
      script: 
      - git submodule update --init
      - sh auto_make_env.sh
      - sh auto_cmake.sh --osx
      - xcodebuild -project ./build-osx/gkENGINE.xcodeproj -scheme ALL_BUILD GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    #- os: osx
    #  osx_image: xcode10
    #  language: objective-c
    #  script: 
    #  - git submodule update --init
    #  - powershell auto_make_env.bat
    #  - sh b.sh --ios
    #  - xcodebuild -project ./build-osx/gkENGINE.xcodeproj -scheme ALL_BUILD GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
