os: Visual Studio 2017 
version: 0.1.{build}

configuration:
- Develop_Latest
#- Release

environment:
  matrix:
  - VS_VERSION: 15 2017
    VS_PLATFORM: x64

before_build:
- cmd: appveyor_setup.bat

build:
  project: c:\projects\gkengine\code\gkENGINE_Vc14.sln
  parallel: true
  verbosity: minimal
